# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore,  QtWidgets
from PyQt5.QtWidgets import QLabel
from PyQt5.QtGui import QPixmap
from ShelfActivatorDefs import getQLabel


def setupUILayout(self,MainWindow):
    MainWindow.setObjectName("MainWindow")
    MainWindow.resize(1640, 700)
    # self.screenheight = 1200   							#self.screenRect.height()
    # self.screenwidth  = 3200   							#self.screenRect.width()
    
    # give layout red bkground


#  from PyQt5 import QtWidgets, QtGui DISGARD AFTER USE

# app = QtWidgets.QApplication([])
# window = QtWidgets.QWidget()

# layout = QtWidgets.QHBoxLayout()
# layout.addWidget(QtWidgets.QPushButton("Button 1"))
# layout.addWidget(QtWidgets.QPushButton("Button 2"))

# container = QtWidgets.QWidget()
# container.setLayout(layout)
# container.setStyleSheet("background-color: red;")  # Set the background color

# window.setLayout(QtWidgets.QVBoxLayout())
# window.layout().addWidget(container)

# window.show()
# app.exec_()
    # Create a style sheet for the title labels
    
    groupboxStyleSheet = """
    QGroupBox {
        border: 2px solid green;
        border-radius: 5px;
        margin-top: 10px;
        font-size: 16px;
    }
    QGroupBox::title {
        subcontrol-origin: margin;
        subcontrol-position: top center;
        color: red;
    }
    """
    
    self.centralwidget = QtWidgets.QWidget(MainWindow)
    self.centralwidget.setObjectName("centralwidget")
    
    spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    
    self.noticeLabel = QtWidgets.QLabel(self.centralwidget)

    # tableWidget
    self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
    self.tableWidget.setObjectName("tableWidget")
    self.tableWidget.cellClicked.connect(self.onTableCellClicked)
    self.tableWidget.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
    self.tableWidget.setColumnCount(0)
    self.tableWidget.setRowCount(0)

    #  create layouts
    self.gridLayout_windowArea = QtWidgets.QGridLayout(self.centralwidget)
    self.gridLayout_windowArea.setObjectName("gridLayout_windowArea")

    # self.appBanner = QtWidgets.QHBoxLayout()
    self.commFieldLayout1 = QtWidgets.QHBoxLayout()
    self.commFieldLayout2 = QtWidgets.QHBoxLayout()
    
    self.comfieldsVBoxLayout = QtWidgets.QVBoxLayout()
    self.installationfieldsVBoxLayout = QtWidgets.QVBoxLayout()

    self.buttonsHBoxLayout = QtWidgets.QHBoxLayout()
 
    self.editAreaGridLayout = QtWidgets.QGridLayout()
    self.buttonAreaGridLayout = QtWidgets.QGridLayout()
    self.tableAreaGridLayout = QtWidgets.QGridLayout()

    self.pushButton_installShelf = QtWidgets.QPushButton(self.centralwidget,clicked=self.updateOrInstallShelf)
    self.pushButton_installShelf.setObjectName("pushButton_installShelf")

    self.pushButton_cancelInstall = QtWidgets.QPushButton(self.centralwidget,clicked=self.restoreShelf)
    self.pushButton_cancelInstall.setObjectName("pushButton_cancelInstall")

    # self.pushButton_cancelInstall.setStyleSheet('QPushButton {background-color: yellow; color: white;}')
    self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget,clicked=self.exitApp)
    self.pushButton_exit.setObjectName("pushButton_exit")

    # self.pushButton_exit.setStyleSheet('QPushButton {background-color: yellow; color: red;}')
    self.cbDeviceTypes = QtWidgets.QComboBox()
    self.cbDeviceTypes.addItems(self.devicetypeListForCombo)
    
    self.cbFactorys = QtWidgets.QComboBox()
    self.cbFactorys.addItems(self.factoryListForCombo)
    # self.cbDeviceTypes.setStyleSheet("QComboBox"
    #                                  "{"
    #                                  "background-color: " + backColorsForCombo[i%2] + ";"
    #                                  "color: " + textColorsForCombo[j%2] + ";"
    #                                  "}")
    
    # screen inputs for shelf installation and activation
    self.IPAddress_input  = QtWidgets.QLineEdit()
    self.IPAddress_input.setFixedWidth(120)
    
    self.port_input = QtWidgets.QLineEdit()
    self.port_input.setFixedWidth(60)

    self.overheadIP_input  = QtWidgets.QLineEdit()
    self.overheadIP_input.setFixedWidth(120)
    
    self.overheadPort_input = QtWidgets.QLineEdit()
    self.overheadPort_input.setFixedWidth(60)

    self.mfDay = QtWidgets.QLineEdit()
    self.mfDay.setFixedWidth(30)
    self.mfMonth = QtWidgets.QLineEdit()
    self.mfMonth.setFixedWidth(30)
    self.mfYear = QtWidgets.QLineEdit()
    self.mfYear.setFixedWidth(40)
    # screen input labels
    self.IPAddress_input_label =  getQLabel(" IP Addr:",-1,50)
    self.port_input_label =  getQLabel(" port:",-1,30)
    self.overheadIP_input_label = getQLabel(" Overhead IP:",-1,70) 
    self.overheadPort_input_label = getQLabel(" Overhead Port:",-1,70) 
    # create an hbox layout for IPAddress_input and port_input
    self.commFieldLayout1 = QtWidgets.QHBoxLayout()
    self.commFieldLayout1.addWidget(self.IPAddress_input_label)
    self.commFieldLayout1.addWidget(self.IPAddress_input)
    self.commFieldLayout1.addWidget(self.port_input_label)
    self.commFieldLayout1.addWidget(self.port_input)

    self.commFieldLayout2.addWidget(self.overheadIP_input_label)
    self.commFieldLayout2.addWidget(self.overheadIP_input)
    self.commFieldLayout2.addWidget(self.overheadPort_input_label)
    self.commFieldLayout2.addWidget(self.overheadPort_input)

    self.comfieldsVBoxLayout.addItem(self.commFieldLayout1)  # ipaddr and port input
    self.comfieldsVBoxLayout.addItem(self.commFieldLayout2)  # ipaddr and port input
    
    self.cbDeviceTypes_label = getQLabel("device type:",-1,25)
    
    self.installationfieldsVBoxLayout.addWidget(self.cbDeviceTypes_label)
    self.installationfieldsVBoxLayout.addWidget(self.cbDeviceTypes)

    self.cbFactorys_label = getQLabel("factory:",-1,25)
    self.installationfieldsVBoxLayout.addWidget(self.cbFactorys_label)
    self.installationfieldsVBoxLayout.addWidget(self.cbFactorys)

    self.dateFieldLayout = QtWidgets.QHBoxLayout()
    self.mfMonth_label = getQLabel("   month:",-1,15)
    self.dateFieldLayout.addWidget(self.mfMonth_label)
    self.dateFieldLayout.addWidget(self.mfMonth)
    self.mfDay_label = getQLabel("   day:",-1,15)
    self.dateFieldLayout.addWidget(self.mfDay_label)
    self.dateFieldLayout.addWidget(self.mfDay)
    self.mfYear_label = getQLabel("  year:",-1,15)
    self.dateFieldLayout.addWidget(self.mfYear_label)
    self.dateFieldLayout.addWidget(self.mfYear)
    
    self.dateFields_label = getQLabel("Manufacture Date:",-1,25)
    self.installationfieldsVBoxLayout.addWidget(self.dateFields_label)
    self.installationfieldsVBoxLayout.addItem(self.dateFieldLayout)
 

    self.editGroupBox_CommSetting = QtWidgets.QGroupBox( self.centralwidget)
    self.editGroupBox_CommSetting.setTitle("Comm Settings:")
    self.editGroupBox_CommSetting.setLayout(self.comfieldsVBoxLayout)
    self.editGroupBox_CommSetting.setStyleSheet(groupboxStyleSheet)
    self.editGroupBox_Install = QtWidgets.QGroupBox(self.centralwidget)
    self.editGroupBox_Install.setTitle("Install/Reinstall Shelf:")
    self.editGroupBox_Install.setLayout(self.installationfieldsVBoxLayout)
    self.editGroupBox_Install.setStyleSheet(groupboxStyleSheet)
    self.buttonsHBoxLayout.addWidget(self.pushButton_installShelf)
    self.buttonsHBoxLayout.addWidget(self.pushButton_cancelInstall)
    self.buttonsHBoxLayout.addWidget(self.pushButton_exit)        

    self.buttonsGroupBox = QtWidgets.QGroupBox( self.centralwidget)
    self.buttonsGroupBox.setLayout(self.buttonsHBoxLayout)

    self.editAreaGridLayout.setObjectName("editAreaGridLayout")
    self.editAreaGridLayout.addWidget(self.editGroupBox_Install,0,0,1,2)
    self.editAreaGridLayout.addWidget(self.editGroupBox_CommSetting,1,0,1,2)
    self.editAreaGridLayout.addItem(spacerItem, 0, 0, 1, 1)
    self.editAreaGridLayout.addItem(spacerItem, 4, 0, 1, 1)
    
    self.buttonAreaGridLayout.setObjectName("buttonAreaGridLayout")
    self.buttonAreaGridLayout.addWidget(self.buttonsGroupBox,0,0,1,2)
   
    
    self.tableAreaGridLayout.setObjectName("tableAreaGridLayout")
    self.tableAreaGridLayout.addWidget(self.noticeLabel, 0, 2, 1, 1)
    self.tableAreaGridLayout.addWidget(self.tableWidget, 1, 2, 1, 1)
    
    # self.appBanner.addWidget(appBannera(self))

    self.gridLayout_windowArea.addLayout(appBanner('images/SHELFACTIVATOR.png'), 0, 0, 1, 1)
    
    self.gridLayout_windowArea.addLayout(self.tableAreaGridLayout, 1, 0, 1, 1)
    self.gridLayout_windowArea.addLayout(self.editAreaGridLayout,  1, 1, 1, 1)
    self.gridLayout_windowArea.addLayout(self.buttonAreaGridLayout,2, 1, 1, 1)
    
    MainWindow.setCentralWidget(self.centralwidget)
    retranslateUi(self,MainWindow)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

def appBanner(appSymbol=''):
     # Load the image using QPixmap
     
     # Set the Logo image on the label
     image_SUNGAL = QLabel()
     image_SUNGAL.setAlignment(QtCore.Qt.AlignCenter)  
     pixmap = QPixmap('images/SUNGAL.png').scaled(70,70) 
     image_SUNGAL.setPixmap(pixmap)
     image_SUNGAL.setStyleSheet("background-color: lightblue;")
     image_SUNGAL.setFixedSize(70, 70)

     # Set the LPOG image on the label
     image_LPOG = QLabel() 
     pixmap = QPixmap('images/LIVINGPOG.png').scaled(200,66)
     image_LPOG.setPixmap(pixmap)
    #  image_LPOG.setStyleSheet("background-color: white;")
    
     mAppBanner = QtWidgets.QHBoxLayout()
     mAppBanner.setSpacing(0)
     mAppBanner.setContentsMargins(0, 0, 0, 10)
     mAppBanner.addWidget(image_SUNGAL)
     mAppBanner.addWidget(image_LPOG)

     image_appsymbol = QLabel()
     if appSymbol !='':
         pixmap = QPixmap(appSymbol).scaled(200,66)
         image_appsymbol.setPixmap(pixmap)
         mAppBanner.addWidget(image_appsymbol)

     return mAppBanner


def retranslateUi(self, MainWindow):
    _translate = QtCore.QCoreApplication.translate
    MainWindow.setWindowTitle(_translate("MainWindow", "Sungal Corp Shelf Activator Utility"))
    self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
    self.pushButton_installShelf.setText(_translate("MainWindow", "Update"))
    self.pushButton_cancelInstall.setText(_translate("MainWindow", "Cancel"))
    self.noticeLabel.setText(_translate("MainWindow", "Please select Shelf from table below"))
